name: hex_toolkit_demo
description: A simple game benchmarking the collision detection performance.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.30.1
  hex_toolkit:
    path: ../hex_toolkit/
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/hex/
