import 'dart:math';

/// A utility class for generating random seeds.
class SeedGenerator {
  static final List<String> _words = [
    'apple',
    'banana',
    'cherry',
    'date',
    'elderberry',
    'fig',
    'grape',
    'honeydew',
    'kiwi',
    'lemon',
    'mango',
    'nectarine',
    'orange',
    'papaya',
    'quince',
    'raspberry',
    'strawberry',
    'tangerine',
    'watermelon',
    'apricot',
    'blackberry',
    'blueberry',
    'coconut',
    'dragonfruit',
    'guava',
    'jackfruit',
    'lime',
    'peach',
    'pear',
    'pineapple',
    'plum',
    'pomegranate',
    'starfruit',
    'avocado',
    'cantaloupe',
    'cranberry',
    'grapefruit',
    'kiwifruit',
    'lychee',
    'mandarin',
    'melon',
    'mulberry',
    'olive',
    'passionfruit',
    'persimmon',
    'rhubarb',
    'tomato',
    'zucchini',
    'almond',
    'cashew',
    'chestnut',
    'hazelnut',
    'macadamia',
    'peanut',
    'pecan',
    'pistachio',
    'walnut',
    'acorn',
    'mountain',
    'river',
    'forest',
    'desert',
    'ocean',
    'valley',
    'plateau',
    'canyon',
    'island',
    'volcano',
    'glacier',
    'meadow',
    'swamp',
    'reef',
    'dune',
    'cave',
    'lake',
    'waterfall',
    'cliff',
    'beach',
    'jungle',
    'tundra',
    'savanna',
    'marsh',
    'hill',
    'plain',
    'basin',
    'bay',
    'delta',
    'fjord',
    'geyser',
    'lagoon',
    'oasis',
    'spring',
    'stream',
    'summit',
    'cape',
    'coast',
    'cove',
    'harbor',
    'isthmus',
    'peninsula',
    'strait',
    'wetland',
    'woodland',
    'prairie',
    'steppe',
    'taiga'
  ];

  /// Generates a random seed in the format "word-word-NNN".
  ///
  /// The seed consists of two random English words separated by a hyphen,
  /// followed by a 3-digit number.
  static String generateRandomSeed() {
    final random = Random();

    // Select two random words
    final word1 = _words[random.nextInt(_words.length)];
    final word2 = _words[random.nextInt(_words.length)];

    // Generate a random 3-digit number (100-999)
    final number = 100 + random.nextInt(900);

    return '$word1-$word2-$number';
  }
}
